### PR TITLE
Orders model/serializer

### PR DESCRIPTION
**Pull request by peterStaggs**
STATUS: READY

Description: This PR builds the Serializer and Model for the 'Orders' table. 

Documentation: YES (comments in code)

Are you making changes to the database? (yes)

Related PRs: N/A

Testing: Migrate the db in a test environment to ensure tables/rows build properly before approving

Notes regarding deployment the contained body of work: This is a simple model, containing only the FK of payment_types.

### CODE REVIEW

**Comment by abbyfleming** [comment]
Hi @stagg0saurus, I'm getting an indentation error. Also, take a look at the Foreign Key name and make sure it matches up. Thank you!

**Comment by abbyfleming** [comment]
screen shot 2017-01-30 at 10 15 37 am The model looks great! I'll look at the serializer next.

**Comment by abbyfleming** [comment]
TabError: inconsistent use of tabs and spaces in indentation

In sublime, under tab size-- convert indentation to tabs

**Comment by abbyfleming** [comment]
No errors, looks great. 🚀

**Comment by ZacharyCline** [comment]
Great Work Pete! Everything is running correctly! 🚀

**Pull request merged**
