### PR TITLE
added PaymentType class

### PR DESCRIPTION
**Pull request by abbyfleming**
STATUS: **READY**

Description: Added a PaymentType class. Added a foreign key for CustomerId, but could not test that part since Customer has not been approved yet.

Documentation: In PaymentType class

Are you making changes to the database? Yes

Related PRs: None

Testing: Outline the steps to test the code in this pull request.
1. Go to teamAPI folder
2. git branch -r
3. Checkout branch
4. Review code
5. Run makemigrations and migrate
6. View in dbbrowser to verify

### CODE REVIEW

**Comment by ZacharyCline** [comment]
update docs on method
Change your string method objects to match fields and you're all set! 
Nice Work and thanks for all the help!

**Comment by ZacharyCline** [comment]
🚀 Looks Great!

**Comment by consumerike** [comment]
🚀

**Comment by peterStaggs** [comment]
:rocket:
screen shot 2017-01-27 at 3 53 30 pm

**Comment by ZacharyCline** [comment]
nice screen shot bruh

**Comment by shawn-mit** [comment]
There is an extra comma at the end of your  " def __str__ "  function so will this make the function immutable as a tuple? Something to watch if we have an issue in the future

:rocket:

**Pull request merged**
