### PR TITLE
In create customers model class

### PR DESCRIPTION
**Pull request by consumerike**
Naming Conventions: 
e.g.-branch: zc-<branch_name>

STATUS: READY

Description: Adds Customers model to model.py

Documentation: See the class documentation

Are you making changes to the database? YES

Related PRs: 

Testing: Outline the steps to test the code in this pull request.
-pull down and check the models class exists

within the TeamApi directory
-Go to the bangazon project folder 
In the command line:
   python manage.py makemigrations Customers
 
Check the migrations folder in the bangazon_api app folder

### CODE REVIEW

**Comment by abbyfleming** [comment]
Check out this link:
http://stackoverflow.com/questions/20958/list-of-standard-lengths-for-database-fields

for standard database lengths and update a few of your fields. Let us know when it's updated and I (we) will review again.

**Comment by abbyfleming** [comment]
Also, checkout the documentation. It looks like the docs should go inside the class.
http://www.django-rest-framework.org/topics/documenting-your-api/#setting-the-description

**Comment by abbyfleming** [comment]
screen shot 2017-01-26 at 11 33 22 am

Nice! 🚀

**Comment by peterStaggs** [comment]
:rocket:

**Comment by ZacharyCline** [comment]
🚀

**Comment by shawn-mit** [comment]
:rocket:

**Pull request merged**
