### PR TITLE
added viewSets, hyperlinked Serializers; actually works now.

### PR DESCRIPTION
**Pull request by peterStaggs**
STATUS: READY

Description: Replaced Serializers with Hyperlinked Serializers; replaced Views with ViewSet; adjusted routes accordingly

Documentation: YES

Are you making changes to the database? (no)

Related PRs: 

Testing: Run Django server and open browser with local host address.

### CODE REVIEW

**Comment by ZacharyCline** [comment]
liftoff!! 🚀

**Comment by consumerike** [comment]
🚀

**Comment by abbyfleming** [comment]
🚀

**Comment by shawn-mit** [comment]
:rocket:

**Pull request merged**
