### PR TITLE
Zc branch

### PR DESCRIPTION
**Pull request by ZacharyCline**
Naming Conventions: 
e.g.-branch: zc-<branch_name>

STATUS: Ready

Ready: Ready to be Merged 🚀 

Description: Define the product data model as well as define the Categories data model

Documentation: Yes

Are you making changes to the database? Yes

Related PRs: Customers--Products needs customers foreign key

Testing: Pull all code down to local system and cd into teamApi dir. Run in command line:
 python manage.py makemigrations bangazon_api
python manage.py migrate

### CODE REVIEW

**Comment by abbyfleming** [comment]
Products Class shows in db browser. customerId & categoryId has been commented out to test. Once customer & category has been approved, I will retest. Documentation looks great! 

screen shot 2017-01-26 at 3 49 59 pm

**Comment by abbyfleming** [comment]
model --> models
snake case for variable names
customer --> customers
category --> categories

**Comment by abbyfleming** [comment]
Nice job, Zach! 🚀 

screen shot 2017-01-27 at 11 57 36 am

**Comment by peterStaggs** [comment]
:rocket:
screen shot 2017-01-27 at 12 02 53 pm

**Comment by consumerike** [comment]
🚀

**Comment by shawn-mit** [comment]
:rocket:

**Comment by ZacharyCline** [comment]
Thanks Team!

**Pull request merged**
