### PR TITLE
initial structure

### PR DESCRIPTION
**Pull request by consumerike**
Naming Conventions: 

STATUS: READY

READY: You think that the PR is ready and are expecting a rocket
ship 

Description: What does the PR do (commit message): creates initial structure for the bangazon project

Documentation: No

Are you making changes to the database? No
Related PRs: 

Testing: Outline the steps to test the code in this pull request.
pull down from github and runserver from command line

### CODE REVIEW

**Comment by abbyfleming** [comment]
I was able to get to the "It worked!" screen. Thanks! 🌮 👍

**Comment by ZacharyCline** [comment]
I got the "It worked!" Screen too!!! 🚀

**Comment by peterStaggs** [comment]
:rocket:

**Comment by shawn-mit** [comment]
🚀

**Pull request merged**
